import 'dart:io';

import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../../../measurements/domain/entities/measurement.dart';
import '../../../patient/domain/entities/patient.dart';
import '../../../surgery_case/domain/entities/surgery_case.dart';

class PdfReportService {
  Future<File> generateReport({
    required Patient patient,
    required SurgeryCase surgeryCase,
    required List<Measurement> measurements,
    String? surgeonName,
  }) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        build: (context) => [
          // Header
          _buildHeader(surgeonName),
          pw.SizedBox(height: 20),

          // Patient info
          _buildSection('Patient Information', [
            _buildInfoRow('Name', patient.fullName),
            if (patient.age != null)
              _buildInfoRow('Age', '${patient.age} years'),
            if (patient.gender != null)
              _buildInfoRow('Gender', patient.gender!),
          ]),
          pw.SizedBox(height: 15),

          // Case info
          _buildSection('Surgery Case', [
            _buildInfoRow('Title', surgeryCase.title),
            _buildInfoRow('Type', surgeryCase.surgeryType),
            _buildInfoRow('Status', surgeryCase.status),
            if (surgeryCase.description != null)
              _buildInfoRow('Description', surgeryCase.description!),
            if (surgeryCase.scheduledDate != null)
              _buildInfoRow(
                'Scheduled Date',
                '${surgeryCase.scheduledDate!.day}/${surgeryCase.scheduledDate!.month}/${surgeryCase.scheduledDate!.year}',
              ),
          ]),
          pw.SizedBox(height: 15),

          // Measurements table
          if (measurements.isNotEmpty) ...[
            _buildSection('Measurements', []),
            pw.SizedBox(height: 5),
            _buildMeasurementsTable(measurements),
          ],

          pw.SizedBox(height: 20),

          // Surgeon notes
          if (surgeryCase.surgeonNotes != null) ...[
            _buildSection('Surgeon Notes', [
              pw.Text(surgeryCase.surgeonNotes!),
            ]),
          ],
        ],
        footer: (context) => pw.Container(
          alignment: pw.Alignment.centerRight,
          margin: const pw.EdgeInsets.only(top: 10),
          child: pw.Text(
            'Generated by Hesti 3D - Page ${context.pageNumber}/${context.pagesCount}',
            style: const pw.TextStyle(
              fontSize: 9,
              color: PdfColors.grey600,
            ),
          ),
        ),
      ),
    );

    // Save to temp directory
    final tempDir = await getTemporaryDirectory();
    final fileName =
        'report_${patient.lastName}_${DateTime.now().millisecondsSinceEpoch}.pdf';
    final file = File('${tempDir.path}/$fileName');
    await file.writeAsBytes(await pdf.save());

    return file;
  }

  pw.Widget _buildHeader(String? surgeonName) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(15),
      decoration: pw.BoxDecoration(
        color: PdfColors.blue50,
        borderRadius: pw.BorderRadius.circular(8),
      ),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text(
                'Hesti 3D',
                style: pw.TextStyle(
                  fontSize: 20,
                  fontWeight: pw.FontWeight.bold,
                  color: PdfColors.blue800,
                ),
              ),
              pw.Text(
                'Surgical Planning Report',
                style: const pw.TextStyle(fontSize: 12, color: PdfColors.grey700),
              ),
            ],
          ),
          pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.end,
            children: [
              if (surgeonName != null)
                pw.Text('Dr. $surgeonName',
                    style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
              pw.Text(
                'Date: ${DateTime.now().day}/${DateTime.now().month}/${DateTime.now().year}',
                style: const pw.TextStyle(fontSize: 10),
              ),
            ],
          ),
        ],
      ),
    );
  }

  pw.Widget _buildSection(String title, List<pw.Widget> children) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          title,
          style: pw.TextStyle(
            fontSize: 14,
            fontWeight: pw.FontWeight.bold,
            color: PdfColors.blue800,
          ),
        ),
        pw.Divider(color: PdfColors.blue200),
        ...children,
      ],
    );
  }

  pw.Widget _buildInfoRow(String label, String value) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 2),
      child: pw.Row(
        children: [
          pw.SizedBox(
            width: 120,
            child: pw.Text(
              label,
              style: pw.TextStyle(
                fontWeight: pw.FontWeight.bold,
                fontSize: 10,
              ),
            ),
          ),
          pw.Expanded(
            child: pw.Text(value, style: const pw.TextStyle(fontSize: 10)),
          ),
        ],
      ),
    );
  }

  pw.Widget _buildMeasurementsTable(List<Measurement> measurements) {
    return pw.Table(
      border: pw.TableBorder.all(color: PdfColors.grey300),
      children: [
        // Header
        pw.TableRow(
          decoration: const pw.BoxDecoration(color: PdfColors.blue50),
          children: [
            _tableCell('Measurement', isHeader: true),
            _tableCell('Value', isHeader: true),
            _tableCell('Unit', isHeader: true),
            _tableCell('Phase', isHeader: true),
            _tableCell('Normal Range', isHeader: true),
          ],
        ),
        // Data rows
        ...measurements.map((m) {
          final range = MeasurementTypes.normalRange(m.measurementType);
          return pw.TableRow(
            children: [
              _tableCell(m.displayName),
              _tableCell(m.value.toStringAsFixed(1)),
              _tableCell(m.unit),
              _tableCell(m.phase),
              _tableCell(range != null
                  ? '${range.$1} - ${range.$2}'
                  : '-'),
            ],
          );
        }),
      ],
    );
  }

  pw.Widget _tableCell(String text, {bool isHeader = false}) {
    return pw.Padding(
      padding: const pw.EdgeInsets.all(5),
      child: pw.Text(
        text,
        style: pw.TextStyle(
          fontSize: 9,
          fontWeight: isHeader ? pw.FontWeight.bold : null,
        ),
      ),
    );
  }
}
